# files to tail.
# These accept standard unix glob matching rules, but with the addition of
# ** as a "super asterisk". ie:
#   "/var/log/**.log"  -> recursively find all .log files in /var/log
#   "/var/log/*/*.log" -> find all .log files with a parent dir in /var/log
#   "/var/log/apache.log" -> just tail the apache log file
#
# See https://github.com/gobwas/glob for more examples
Files = ["testdata/*.log"]
# Read file from beginning.
FromBeginning = false
# Whether file is a named pipe
Pipe = false
# WatchMethod inotify/poll
WatchMethod = "inotify"
# OffsetSavePrefix logtail
OffsetSavePrefix = "logtail"

# 日志行提取表达式
Capture="contains customerVerify [End] | split by=^_^ keeps=1 | anchor start=[ | cut :-1"
# POST URL
# PostURL  = "http://127.0.0.1:8812"
